name: Deploy to ReflexCloud

on:
  push:
    branches:
      - lendemor/deploy_pipeline

jobs:
    setup-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.generate-matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v3
            - name: Generate Matrix
              id: generate-matrix
              run: |
                FOLDERS=$(ls -d */ | sed 's|/||g' | jq -R -s -c 'split("\n")[:-1]')
                echo "Found subfolders: $FOLDERS"
                echo "folders=$FOLDERS" >> $GITHUB_ENV
            - name: Debug output (matrix)
              run: |
                echo "Subfolders: ${{ env.folders }}"
