name: Deploy to ReflexCloud

on:
  push:
    branches:
      - lendemor/deploy_pipeline

jobs:
    setup-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.generate-matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v3
            - name: Generate Matrix
              id: generate-matrix
              run: |
                FOLDERS=$(ls -d */ | sed 's|/||g' | jq -R -s -c 'split("\n")[:-1]')
                echo "folders=$FOLDERS" >> $GITHUB_OUTPUT
            - name: Debug output (matrix)
              run: |
                echo "Subfolders: ${{ env.folders }}"

    deploy:
        needs: setup-matrix
        runs-on: ubuntu-latest
        strategy:
            matrix:
                folder: ${{fromJson(needs.setup-matrix.outputs.folders)}}
        steps:
            - uses: actions/checkout@v3
            - name: Deploy to ReflexCloud
              run: |
                echo "Deploying ${{ matrix.folder }}"
                # Add your deployment script here
                # Example: deploy.sh ${{ matrix.folder }}