name: Deploy to ReflexCloud

on:
  push:
    branches:
      - lendemor/deploy_pipeline

jobs:
    setup-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.generate-matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v3
            - name: Generate Matrix
              id: generate-matrix
              run: 
                echo "::set-output name=folders::$(ls -d */ | sed 's|/||g' | jq -R -s -c 'split("\n")[:-1]')"
            - name: Debug output (matrix)
              run: |
                echo "matrix=$folders"
