name: deploy

on:
  push:
    branches:
      - lendemor/deploy_pipeline

jobs:
    setup-matrix:
        runs-on: ubuntu-latest
        outputs:
            folders: ${{ steps.generate-matrix.outputs.folders }}
        steps:
            - uses: actions/checkout@v3
            - name: Generate Matrix
              id: generate-matrix
              run: |
                FOLDERS=$(ls -d */ | sed 's|/||g' | jq -R -s -c 'split("\n")[:-1]')
                echo "folders=$FOLDERS" >> $GITHUB_OUTPUT
            - name: Debug output (matrix)
              run: |
                echo "Subfolders: ${{ env.folders }}"

    deploy:
        needs: setup-matrix
        runs-on: ubuntu-latest
        strategy:
            matrix:
                folder: ${{fromJson(needs.setup-matrix.outputs.folders)}}
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                pip install -r ${{ matrix.folder }}/requirements.txt
            - name: Set environment dynamically
              id: set-env
              run: |
                  # Convert subfolder name to uppercase to match the secret naming convention
                  DYNAMIC_ENV_NAME="ENV_${{ matrix.folder }}"
                  # Export the secret's value
                  echo "EXTRA_ENV=--env ${{ secrets[DYNAMIC_ENV_NAME] }}" >> $GITHUB_ENV
            - name: Deploy to ReflexCloud
              env:
                REFLEX_AUTH_TOKEN: ${{ secrets.REFLEX_AUTH_TOKEN }}
              run: |
                chmod +x deploy.sh
                ./deploy.sh ${{ matrix.folder }} "$EXTRA_ENV"